<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>4.0.0</Version>
		<RootNamespace>ToolBX.$(AssemblyName)</RootNamespace>
		<PackageId>ToolBX.$(AssemblyName)</PackageId>
		<Product>ToolBX.$(AssemblyName)</Product>
		<Authors>Mathieu Moreault</Authors>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<RepositoryUrl>https://github.com/Moreault/Unicity</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Moreault/Unicity</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>Extensions for auto-incrementing numbers in non-database settings.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>unicity.png</PackageIcon>
		<IsAotCompatible>true</IsAotCompatible>
		<IsTrimmable>true</IsTrimmable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>Unicity.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\unicity.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
